src/__tests__/connectors/JsonRPCWeb3Connector.test.ts
src/__tests__/managers/ContractManager.test.ts
src/__tests__/utils/conversions.test.ts
src/connectors/AbstractWeb3Connector.ts
src/managers/ContractManager.ts
src/utils/conversions.ts

- Moving changeTransaction method to ContractManager class.
- Added deprecation notice warning message to changeTransaction method on abstract connector class.
- Tests
...

[Ws 78] Moving changeTransaction from connector to contract manager

---

.github/workflows/ci.yml

- Added SEMANTIC_RELEASE_GITHUB_TOKEN
- Updated actions from v2 to v3
- Added conditional to run lint and test actions
...

[WS-85] Fix Github CI

---

src/__tests__/gaming/ExtendedNFT721Manager.test.ts
src/__tests__/gaming/ExtendedToken20Manager.test.ts
src/gaming/ExtendedNFT721Manager.ts
src/gaming/ExtendedToken20Manager.ts

- Deprecate ExtendedNFT721Manager.
- Deprecate ExtendedToken20Manager.
...

WS-92 Deprecate Extended Managers

---

.github/workflows/ci.yml

- renamed release env
- update based on [configuration file](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md) and the error
`[3:31:05 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[3:31:05 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://[secure]@github.com/ripio/sdkjs.git HEAD:develop`

[WS-85] Fix CI v2

---

.github/workflows/ci.yml

- approach using token on checkout step
...

[WS-85] CI update v3

---

src/__tests__/managers/ContractManager.test.ts
src/__tests__/utils/validations.test.ts
src/managers/ContractManager.ts
src/utils/validations.ts

- Add implements to ContractManager.
- Add implementsFuntion on utils file.
...

WS-93 check contract function

---

.github/workflows/ci.yml

A concise description of what has been done to solve the task.
...

downgrading checkout version to v2

---

src/nft/storage/Resource.ts
src/nft/storage/StorageType.ts

- Added StorageType and Resourse interfaces

WS-89 Create StorageType and ResourcesType

---

src/__tests__/connectors/JsonRPCWeb3Connector.test.ts
src/__tests__/gaming/ExtendedNFT721Manager.int.test.ts
src/__tests__/gaming/ExtendedNFT721Manager.test.ts
src/__tests__/gaming/ExtendedToken20Manager.int.test.ts
src/__tests__/gaming/ExtendedToken20Manager.test.ts
src/__tests__/utils/conversions.test.ts
src/connectors/AbstractWeb3Connector.ts
src/types/interfaces.ts
src/utils/conversions.ts

- Added changeBalanceTransaction method on abstract connector to change a transfer balance transaction.
- transferBalance method call now returns a connectorResponseExtended with the new change method.
- manager parameter is now mandatory in extendTransactionResponse, since it is only called in the execute function from ContractManager.
- Added/updated tests
- Suppress console.warn in extended classes tests.

Ws 79 change transaction function change balance

---

src/__tests__/nft/NFT.test.ts
src/nft/NFT.ts
src/nft/index.ts
src/types/interfaces.ts

WS-94 - NFT class

---

package-lock.json
package.json
src/__tests__/connectors/BrowserWeb3Connector.test.ts
src/__tests__/nft/storage/ResourceHttp.test.ts
src/__tests__/nft/storage/StorageHttp.test.ts
src/nft/storage/ResourceHttp.ts
src/nft/storage/StorageHttp.ts

- Addd `StorageHttp` and `ResourceHttp` classes
- Jest updated, so it can work with axios

Ws 101 storage create http storage

---

src/__tests__/nft/storage/StorageAws.test.ts
src/__tests__/nft/storage/StorageHttp.test.ts
src/__tests__/nft/storage/StorageIpfs.test.ts
src/nft/storage/StorageAws.ts
src/nft/storage/StorageHttp.ts
src/nft/storage/StorageIpfs.ts
src/nft/storage/StorageType.ts

- Added upload methods to StorageType interface
- Added upload methods to StorageIpfs
- Added upload methods to StorageAws and StorageHttp (not implemented)

Ws 103 storage create ipfs storage upload functions

---

src/__tests__/connectors/JsonRPCWeb3Connector.test.ts
src/connectors/AbstractWeb3Connector.ts

- Updated speedUpGas calculations using the speedUpPercentage or the provided gasSpeed.
- Updated related tests.
...

[WS-105] Speed up gas method updated

---

src/__mocks__/@aws-sdk/client-s3.ts
src/__tests__/nft/storage/StorageAws.test.ts
src/nft/storage/Resource.ts
src/nft/storage/StorageAws.ts

- Added upload methods to StorageAws
- Fix getJsonData return type

Ws 104 storage create aws storage upload functions

---

CHANGELOG.md

Remove unnecessary entries from changelog

remove unnecesary changelog entries

---

CHANGELOG.md
package-lock.json
package.json

- Update changelog
- Update version on package

Update version and changelog

---

package-lock.json
packages/sdk/src/__tests__/connectors/JsonRPCWeb3Connector.test.ts
packages/sdk/src/connectors/AbstractWeb3Connector.ts

- Added getBlock method on abstract connector class
- Updated return type as getTransaction won't return null
...

[WS-108] Get block method on Abstract connector

---

package-lock.json
packages/nft/README.md
packages/sdk/README.md
packages/storageAws/README.md
packages/storageHttp/README.md
packages/storageIpfs/README.md

Add packages readme

---

package-lock.json
package.json

- semantic-release/github plugin added.

adding semantic-release github plugin

---

package-lock.json
packages/nft/package.json

- Added `uint8arrays` to nft package

fix: add uint8arrays as a dependency

---

packages/nft/src/NFTHandler.ts
packages/nft/src/__tests__/NFTHandler.test.ts
packages/nft/src/index.ts
packages/sdk/src/types/errors.ts

- Add getNFTListByOwner function.
...

WS-133 - Get nft list by owner

---

packages/storageIpfs/src/StorageIpfs.ts
packages/storageIpfs/src/__tests__/StorageIpfs.test.ts

- Add storeBase64Image to StorageIpfs
...

WS-138 - Add storeBase64Image to StorageIpfs

---

babel.config.json
package-lock.json
package.json
packages/sdk/src/__tests__/managers/ContractManager.test.ts
packages/sdk/src/managers/ContractManager.ts
tsconfig.json

- Add configuration to use decorators
- Fix check contract manager activation on implements function
...

Decorators & Bugs

---

babel.config.json
package-lock.json
package.json
packages/nft/src/NFTHandler.ts
packages/nft/src/__tests__/NFTHandler.test.ts
packages/nft/src/types/interfaces.ts
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/sdk/src/__tests__/managers/ContractManager.test.ts
packages/sdk/src/managers/ContractManager.ts
packages/sdk/src/types/errors.ts
tsconfig.json

- Add NFTHandler create method
- Refactor NFTHandler class

Ws 126 nft create nft

---

docs/sdk-nft/README.md

Add docs for:
- NFTImageFactory 
- NFTJsonFactory
- NFTJsonImageFactory
- NFTHandler

Ws 130 nft create nft and change nft documentation

---

packages/nft/src/NFTHandler.ts
packages/nft/src/__tests__/NFTHandler.test.ts
packages/nft/src/__tests__/utils/decorators.test.ts
packages/nft/src/utils/decorators.ts
packages/nft/src/utils/index.ts
packages/sdk/src/types/errors.ts

- Add getLastNFTId
- Add ManagerMustActive decorator
- Refactor NFTHandler
...

WS-140 - Add getLastNFTId

---

docs/sdk-nft/README.md

add getLastNFTId docs

---

docs/sdk-nft/README.md
docs/sdk-storage-aws/README.md
docs/sdk-storage-http/README.md
docs/sdk-storage-ipfs/README.md
docs/sdk/README.md
packages/nft/README.md
packages/sdk/README.md
packages/storageAws/README.md
packages/storageHttp/README.md
packages/storageIpfs/README.md

- Replace `rgc` with `ripio` on docs

WS-156 [Documentation] rgc x ripio

---

jest.config.js
package-lock.json
package.json
packages/modalConnector/README.md
packages/modalConnector/jest.config.js
packages/modalConnector/package.json
packages/modalConnector/src/ModalConnector.ts
packages/modalConnector/src/__mocks__/@wagmi/core.ts
packages/modalConnector/src/__mocks__/@web3modal/ethereum.ts
packages/modalConnector/src/__mocks__/@web3modal/html.ts
packages/modalConnector/src/__tests__/ModalConnector.test.ts
packages/modalConnector/src/chains/index.ts
packages/modalConnector/src/index.ts
packages/modalConnector/tsconfig.cjs.json
packages/modalConnector/tsconfig.esm.json
packages/modalConnector/tsconfig.json
packages/sdk/src/__tests__/connectors/BrowserWeb3Connector.test.ts
packages/sdk/src/__tests__/connectors/JsonRPCWeb3Connector.test.ts
packages/sdk/src/managers/ContractManager.ts

- Added `sdk-modal-connector` package
- Modified `ContractManager` to use `AbstractWeb3Connector` instead of `BrowserWeb3Connector` and `JsonRPCWeb3Connector `

Ws 159 new package sdk modal connector

---

docs/README.md
docs/sdk-modal-connector/README.md
docs/sdk-nft/README.md
docs/sdk-storage-aws/README.md
docs/sdk-storage-http/README.md
docs/sdk-storage-ipfs/README.md
docs/sdk/README.md
packages/modalConnector/README.md
packages/nft/README.md
packages/sdk/README.md
packages/storageAws/README.md
packages/storageHttp/README.md
packages/storageIpfs/README.md

- Added `sdk-modal-connector` docs

add modal-connector docs

---

package-lock.json
packages/modalConnector/package.json

- Use patch releases on `@wagmi/core` `@web3modal/ethereum` and `@web3modal/html` to prevent breaking changes

WS-164 [Modal Connector] Wagmi and Web3modal error

---

packages/sdk/src/__tests__/connectors/BrowserWeb3Connector.test.ts
packages/sdk/src/connectors/BrowserWeb3Connector.ts

- Added a reload on chainChanged event

Ws 165 fix limitation issue with get fee data function on network change event

---

package-lock.json
packages/modalConnector/package.json
packages/modalConnector/src/ModalConnector.ts
packages/modalConnector/src/__mocks__/@web3modal/ethereum.ts
packages/modalConnector/src/__tests__/ModalConnector.test.ts

- Updated `@wagmi/core` to `~0.10.11`
- Updated `@web3modal/ethereum` to `~2.3.7`
- Updated `@web3modal/html` to `~2.3.7`
- Updated `ModalConnector` with updated imports

feat: update wagmi and web3modal
